# Generated by Django 4.2.7 on 2023-11-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_questao_alternativa_correta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='alternativa_submetida',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
