# Generated by Django 4.2.7 on 2023-11-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_questao_alternativa_submetida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='alternativa_submetida',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
